WIP:merge glance modification from eayunstack-upgrade version 3.0.1
eayunstack/fuel-library pull request #52
Opened 2017-09-05 01:53 UTC by blkart

Signed-off-by: blkart <blkart.org@gmail.com>

2017-09-05 02:15 UTC, huntxu commented
会否考虑将这一系列的更新合并在一个pull request中暂时加上WIP的标记。便于以后各种追溯和管理。如我们在 #2, #3, #4 中那样

2017-09-05 02:31 UTC, blkart commented
更新工作是两个人一起做的，合到一个 pr 里可能不太好弄。目前是按照组件分的 pr，感觉也没问题。

2017-09-26 03:06 UTC, huntxu requested changes
少了glance-registry的改动？

2017-10-10 10:39 UTC, blkart commented
3.0.1 版本 ceilometer 去掉了 image(glance) 相关的统计项，glance-registry 相关改动不需要再修改。

2017-10-10 10:45 UTC, huntxu approved these changes

2017-10-12 04:08 UTC, merged